### ISSUE TITLE
Website is currently down

### ISSUE THREAD

**Issue by cthoyt** [OpenBEL/openbel-framework-resources#16]
http://resources.openbel.org/belframework/ and http://resource.belframework.org/belframework/ are both down

**Comment by wshayes** [comment]
Thanks for pointing those out. Just removed them.  We lost those servers in transferring things over to TranSMART.  Github is the single source now.

**Comment by cthoyt** [comment]
If I recall correctly, GitHub frowns on using their service as a file server. We have a temporary solution for publicly hosting these namespaces on Fraunhofer servers outlined in https://github.com/pybel/pybel-resources that we hope to replace with a more permenant namespace management system ASAP

**Comment by wshayes** [comment]
I can check on mirroring these to S3 but if you are already hosting them on ownCloud - can't we just update the URL to that?  I'm happy to update the resources.openbel.org subdomain to point to them.

**Comment by wshayes** [comment]
TranSMART fixed the Openbel.org resources and wiki server.  The belframework.org domain has been retired (not continuing to pay for it).  I've re-added the http://resources.openbel.org/belframework/  link to the github README for the belframework resources.

**Comment by cthoyt** [comment]
That's great news. Thanks
